---

- name: Copying nodejs compiled file
  copy:
    src: node
    dest: "{{ binary_path }}"
    mode: a+rx
  become: yes

- name: Installing npm
  yum:
    name: "{{npm_pkg_name}}"
    state: present
  become: yes

- name: Adding CentOS EPEL repository
  yum:
    name: "{{epel_pkg_name}}"
    state: present
  become: yes

- name: Installing Nginx
  yum:
    name: "{{nginx_pkg_name}}"
    state: present
  become: yes

- name: Configuring Nginx
  template:
    src: nginx.conf.j2
    dest: "{{fileconf_path}}"
  become: yes

- name: Configuring Nginx service
  template:
    src: nginx.service.j2
    dest: "{{fileservice_path}}"
  become: yes

- name: Reloading systemctl
  command: systemctl daemon-reload
  become: yes

- name: Pushing application
  copy:
    src: soc-ihm
    dest: "{{directory_application_path}}"
  become: yes

- name: Starting Nginx service
  service:
    name: nginx
    state: restarted
    enabled: yes
  become: yes
